### ISSUE TITLE
Try to seek for race conditions occurring in Actions only

### ISSUE THREAD

**Issue by bertllll** [MASQ-Project/Node#445]
I've experienced them more than little times in:  Node/masq/communication/communication_manager 
at more places in there.

**Comment by bertllll** [comment]
I got this despite this area of our code could not be affected by the worked card (GH-381). Happened after a break from seeing any strangely failing tests. When a new Rust version came.

thread 'main' panicked at 'ClientListenerThread could not be restarted: Timeout', D:\a\Node\Node\masq\src\communications\connection_manager.rs:455:23
stack backtrace:
   0:     0x7ff74c24187e - std::backtrace_rs::backtrace::dbghelp::trace
test communications::connection_manager::tests::handles_outgoing_fire_and_forget_messages_to_dead_server ... FAILED
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff74c24187e - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff74c24187e - std::sys_common::backtrace::_print_fmt
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b\/library\std\src\sys_common\backtrace.rs:67
                             
  
**communications::connection_manager::tests::handles_outgoing_fire_and_forget_messages_to_dead_server**

**Comment by bertllll** [comment]
This problem occurred at the same day as the previous but I didn't have time to report it. It showed itself once and in the next run Actions did not complain though I did no changes in the code. 

![log multinode test](https://user-images.githubusercontent.com/65427484/107931689-eabfd380-6f7c-11eb-9e48-094dbc3c561f.png)

**multinode_integration_tests/tests/connection_termination_test**

**Comment by dnwiebe** [comment]
One of the multinode tests failed: **provided_and_consumed_services_are_recorded_in_databases**.
[logs_473.zip](https://github.com/MASQ-Project/Node/files/6010133/logs_473.zip)

The same test...Bert.
[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/7092169/2_Build.node.on.ubuntu-latest.txt)

Again
[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/7436567/2_Build.node.on.ubuntu-latest.txt)

**Comment by bertllll** [comment]
windows: `tls_through_node_test` (integration); I know this test because that's the one which permanently fails on my Win machine.

[logs_530.zip](https://github.com/MASQ-Project/Node/files/6157723/logs_530.zip)

**Comment by bertllll** [comment]
MacOS: Node: unit_tests:
initialize_with_clandestine_port_produces_expected_clandestine_discriminator_factories_vector

[logs_599.zip](https://github.com/MASQ-Project/Node/files/6264178/logs_599.zip)

**Comment by bertllll** [comment]
This is unfortunate. By all evidences, GitHub stopped to support zipped packages and these ours which are attached to the comments here are inaccessible by now. I'd be happy if I was wrong. 


Now it accept zipped folders again...so...I don't know. But we lost the old ones.

**Comment by bertllll** [comment]
**handle_startup_and_shutdown_integration**

This test was renovated for this card, MASQ-Project/MASQ-Node-issues#386, however, usually it passes, this time it didn't. Maybe RC.

[3_Build node on windows-latest.txt](https://github.com/MASQ-Project/Node-issues/files/6316666/3_Build.node.on.windows-latest.txt)
...
[3_Build node on windows-latest.txt](https://github.com/MASQ-Project/Node-issues/files/6472246/3_Build.node.on.windows-latest.txt)

And another one:
22.6.21
[3_Build node on windows-latest.txt](https://github.com/MASQ-Project/Node-issues/files/6693596/3_Build.node.on.windows-latest.txt)

Hmmm...this is growing up fast
24.6.2021
[3_Build node on windows-latest.txt](https://github.com/MASQ-Project/Node-issues/files/6708219/3_Build.node.on.windows-latest.txt)
26.6.2021 twice
[3_Build node on windows-latest.txt](https://github.com/MASQ-Project/Node-issues/files/6720158/3_Build.node.on.windows-latest.txt)
[3_Build node on windows-latest.txt](https://github.com/MASQ-Project/Node-issues/files/6720167/3_Build.node.on.windows-latest.txt)

In MASQ-Project/MASQ-Node-issues#451, I was trying to fix this by adding a piece of logic to the code. It may happen that this error will evaporate then.  

Nope, without a relief, the frequency of this failure may even have increased.


[3_Build node on windows-latest.txt](https://github.com/MASQ-Project/Node-issues/files/7236345/3_Build.node.on.windows-latest.txt)

27th of September 
I tried to prevent this issue more reliably with a modification in fallback - connection manager. Card MASQ-Project/MASQ-Node-issues#305. 

4th October 
Not fixed yet

**Comment by bertllll** [comment]
**handle_redirect_order_disappoints_waiting_conversations_with_resend_or_graceful**

Maybe newly created RC after I did a lot of modifications (GH-386) in the UI where some could affect the connection_manager in his work, well, maybe not. 

[3_Build node on windows-latest.txt](https://github.com/MASQ-Project/Node-issues/files/6316709/3_Build.node.on.windows-latest.txt)

**Comment by bertllll** [comment]
**communications::connection_manager::tests::handles_listener_fallback_from_node**

Another test that I don't remember failing. Again MASQ-Project/MASQ-Node-issues#386.

[3_Build node on windows-latest.txt](https://github.com/MASQ-Project/Node-issues/files/6317062/3_Build.node.on.windows-latest.txt)

**Comment by bertllll** [comment]
**provided_and_consumed_services_are_recorded_in_databases**

Multinode-integration-test...I remember seeing this before. Yup. Look up there.

Again, this was during MASQ-Project/MASQ-Node-issues#386.

[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/6317208/2_Build.node.on.ubuntu-latest.txt)

7.7.22
[2_Build.node.on.ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/9067427/2_Build.node.on.ubuntu-latest.txt)

**Comment by bertllll** [comment]
**connection_manager::tests::handles_fire_and_forget_outgoing_message**

I thought that this had been seen multiple times, but I'm not sure now. 

[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/6377141/2_Build.node.on.ubuntu-latest.txt)

This time on MacOs
[1_Build node on macOS-latest.txt](https://github.com/MASQ-Project/Node-issues/files/6711084/1_Build.node.on.macOS-latest.txt)

Again...
[2_Build node on macOS-latest.txt](https://github.com/MASQ-Project/Node-issues/files/9217736/2_Build.node.on.macOS-latest.txt)

**Comment by bertllll** [comment]
**test_utils::mock_websockets_server::tests::conversational_and_broadcast_messages_can_work_together_testing_corner_cases**

mac_os

[1_Build node on macOS-latest.txt](https://github.com/MASQ-Project/Node-issues/files/6615707/1_Build.node.on.macOS-latest.txt)

**Comment by bertllll** [comment]
I'm adding this after a while passed from when it happened; I found it my Downloads folder. 

**blockchain::blockchain_interface::tests::blockchain_interface_non_clandestine_retrieves_transactions**
[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/6693630/2_Build.node.on.ubuntu-latest.txt)

1st of Sep
[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/7092207/2_Build.node.on.ubuntu-latest.txt)

23rd of Sep
[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/7216288/2_Build.node.on.ubuntu-latest.txt)

**Comment by bertllll** [comment]
similarly, I found this: 

**websocket_supervisor::tests::send_msg_fails_to_look_up_client_to_send_to**
[3_Build node on windows-latest.txt](https://github.com/MASQ-Project/Node-issues/files/6693655/3_Build.node.on.windows-latest.txt)

**Comment by bertllll** [comment]
Seems like we've got a new one. 
**blockchain::blockchain_interface::tests::blockchain_interface_non_clandestine_retrieve_transactions_returns_an_error_if_a_response_with_data_that_is_too_long_is_returned**
[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/7092253/2_Build.node.on.ubuntu-latest.txt)

**Comment by bertllll** [comment]
Too many of blockchain_interface lately, feeling suspicious.
**blockchain::blockchain_interface::tests::blockchain_interface_non_clandestine_retrieve_transactions_ignores_transaction_logs_that_have_no_block_number**
[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/7092279/2_Build.node.on.ubuntu-latest.txt)

From earlier:
[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/7092352/2_Build.node.on.ubuntu-latest.txt)

A very old one..
[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/7092423/2_Build.node.on.ubuntu-latest.txt)

[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/7236356/2_Build.node.on.ubuntu-latest.txt)

**Comment by bertllll** [comment]
**neighborhood::gossip_acceptor::tests::standard_gossip_containing_unfamiliar_node_addrs_leads_to_them_being_ignored**
[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/7092374/2_Build.node.on.ubuntu-latest.txt)

**Comment by bertllll** [comment]
Multinode...
**provided_and_consumed_services_are_recorded_in_databases**
[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/7092389/2_Build.node.on.ubuntu-latest.txt)

Don't know why yet, but now a time of a lot of failures in multinode tests has come. 

Another: 
**provided_and_consumed_services_are_recorded_in_databases**
[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/7167861/2_Build.node.on.ubuntu-latest.txt)

[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/7237615/2_Build.node.on.ubuntu-latest.txt)

[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/7478276/2_Build.node.on.ubuntu-latest.txt)

Seems like the manifestation of the error can be slightly different at different times.

**Comment by bertllll** [comment]
multinode
**downed_nodes_not_offered_in_passes_or_introductions**
[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/7162082/2_Build.node.on.ubuntu-latest.txt)

[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/7613551/2_Build.node.on.ubuntu-latest.txt)

21/12/2022
[logs_1396.zip](https://github.com/MASQ-Project/Node-issues/files/10279038/logs_1396.zip)

**Comment by bertllll** [comment]
**blockchain::blockchain_interface::tests::blockchain_interface_non_clandestine_can_retrieve_eth_balance_of_a_wallet**
[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/7162100/2_Build.node.on.ubuntu-latest.txt)

**Comment by FinsaasGH** [comment]
multinode
multiple_stream_zero_hop_test
[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/7390441/2_Build.node.on.ubuntu-latest.txt)

**Comment by bertllll** [comment]
**pass_args_or_print_messages_work_under_fine_lock_for_eof**

I guess this is a rare one. I suggest just to increase the multiplier in the assertion like from 3 to 4 or something. I know there is a couple of tests like this and this was the latest I added, maybe the chosen multiplier doesn't fit as well as for the other tests, I think its value could be a bit test specific. 

[1_Build node on macOS-latest.txt](https://github.com/MASQ-Project/Node-issues/files/7449934/1_Build.node.on.macOS-latest.txt)

**Comment by bertllll** [comment]
**tls_through_node_integration**

This one is really rare in Actions I think, on the other hand we come to see it quite often on dev machines. Speaking mainly for myself (maybe occurred almost all the time) but I also saw it at Utkarsh.
 
[3_Build node on windows-latest.txt](https://github.com/MASQ-Project/Node-issues/files/8031286/3_Build.node.on.windows-latest.txt)

**Comment by dnwiebe** [comment]
The multinode test tls_end_to_end_routing_test hung for most of five hours. We don't know why, but here's the log.

[logs_830.zip](https://github.com/MASQ-Project/Node-issues/files/8060625/logs_830.zip)
[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/8060638/2_Build.node.on.ubuntu-latest.txt)

**Comment by utkarshg6** [comment]
**graph_connects_but_does_not_over_connect**
[1_build.txt](https://github.com/MASQ-Project/Node-issues/files/8178375/1_build.txt)
[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/8178377/2_Build.node.on.ubuntu-latest.txt)

**Comment by bertllll** [comment]
**http_through_node_integration**

[1_Build node on macOS-latest.txt](https://github.com/MASQ-Project/Node-issues/files/8500603/1_Build.node.on.macOS-latest.txt)

**Comment by bertllll** [comment]
**masq_erc20_contract_exists_on_polygon_mumbai_integration**

[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/8572665/2_Build.node.on.ubuntu-latest.txt)
